version = 0.1

#######################################
# GLOBAL (common settings)
#######################################
[default.global.parameters]
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

#######################################
# DEV ENVIRONMENT
#######################################
[dev.deploy.parameters]
stack_name = "aws-lambda-nodejs-example-dev"
resolve_s3 = true
s3_prefix = "aws-lambda-nodejs-example-dev"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "Environment=dev"

#######################################
# PROD ENVIRONMENT
#######################################
[prod.deploy.parameters]
stack_name = "aws-lambda-nodejs-example-prod"
resolve_s3 = true
s3_prefix = "aws-lambda-nodejs-example-prod"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
parameter_overrides = "Environment=prod"

#######################################
# OPTIONAL (local testing)
#######################################
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
