name: Deploy SAM Function

on:
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: "Choose full stack deploy or single-function code deploy"
        required: true
        type: choice
        options:
          - function
          - full
        default: function

      function_name:
        description: "SAM logical resource id (for example: GetUserFunction)"
        required: true
        type: choice
        options:
          - AddUserFunction
          - GetUserFunction
          - GetAllUsersFunction
          - HelloWorldFunction
          - QuotesScraperFunction
        default: GetUserFunction

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::922763798417:role/GitHubActionsSamDeployRole
          aws-region: us-east-1

      - name: Show selected inputs
        run: |
          echo "Deploy mode: ${{ inputs.deploy_mode }}"
          echo "Function name: ${{ inputs.function_name }}"

      - name: Build selected function
        if: ${{ inputs.deploy_mode == 'function' }}
        run: sam build ${{ inputs.function_name }}

      - name: Sync selected function code only
        if: ${{ inputs.deploy_mode == 'function' }}
        shell: bash
        run: |
          yes | sam sync \
            --stack-name aws-lambda-nodejs-example \
            --code \
            --resource-id ${{ inputs.function_name }} \
            --no-watch \
            --no-skip-deploy-sync \
            --no-dependency-layer

      - name: Build full application
        if: ${{ inputs.deploy_mode == 'full' }}
        run: sam build

      - name: Deploy full stack
        if: ${{ inputs.deploy_mode == 'full' }}
        run: |
          sam deploy \
            --stack-name aws-lambda-nodejs-example \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM
