name: Deploy SAM App

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::922763798417:role/GitHubActionsSamDeployRole
          aws-region: us-east-1   # change if needed

      - name: SAM build
        run: sam build

      - name: SAM deploy
        run: |
          sam deploy \
            --stack-name aws-lambda-nodejs-example \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --capabilities CAPABILITY_IAM
